@ExpenseManagement.Api_HostAddress = http://localhost:5258

POST {{ExpenseManagement.Api_HostAddress}}/api/employee
Accept: application/json
Content-Type: application/json

{
  "firstName": "jewel",
  "lastName": "Doe",
  "email": "jewel.doe@example.com",
  "phoneNumber": "+8801712345685",
  "address": "123 Main Street",
  "city": "Denmark",
  "state": "Copenhagen",
  "zipCode": "15205",
  "country": "Denmark",
  "dateOfBirth": "1995-06-15",
  "salary": 75000.00,
  "position": "Software Engineer",
  "departmentId": 1,
  "joiningDate": "2026-10-03",
  "password": "Test@12345"
}

###
